function [fitresult, gof] = createFit_2Exp_ecdf(x, SurvivlF,ColorOption)
%CREATEFIT(X,SURVIVLF)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: SurvivlF
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 17-Dec-2021 19:05:26


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, SurvivlF );

% Set up fittype and options.
ft = fittype('1-a*exp(-b*x)-c*exp(-d*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
% opts.StartPoint = [1.68876878154546 -0.0936748590329067 -0.958710979239425 -0.0697720266394217];
opts.StartPoint = [1 1 1 1];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData);
h(1).Color = ColorOption;
h(2).Color = ColorOption;
% legend( h, 'SurvivlF vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% xlabel( 'x', 'Interpreter', 'none' );
% ylabel( 'SurvivlF', 'Interpreter', 'none' );
grid on


