function [fitresult, gof] = createFit_custom(x, F,ColorOption)
%CREATEFIT(X,F)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: F
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Dec-2021 19:59:27


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, F );

% Set up fittype and options.
ft = fittype( 'a*exp(-b*x)+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.353719061594749 0.45746847873321 0.988974791004206];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
h(1).Color = ColorOption;
h(2).Color = ColorOption;
% legend( h, 'F vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% xlabel( 'x', 'Interpreter', 'none' );
% ylabel( 'F', 'Interpreter', 'none' );
grid on
